<footer class="mt-auto text-white-50">
    <p>Master Course &copy All rights reserved - <?= date('Y'); ?></p>
</footer>
</div>

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="../../resources/dist/js/particles.js"></script>
<script src="../../resources/dist/js/app.js"></script>
<script src="../../resources/dist/js/lib/stats.js"></script>

</html>