<!doctype html>
<html lang="en" class="h-100">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <title>Master Course</title>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
  <link rel=" stylesheet" href="../../resources/dist/css/personstyle.css">
  <link rel="stylesheet" href="../../resources/dist/css/style.css">

</head>

<body class="d-flex h-100 text-center text-white bg-dark" id="particles-js">