<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0">Master Course</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link active" aria-current="page" href="<?= HOME ?>">Home</a>
                <a class="nav-link" href="<?= HOME ?>about">About</a>
                <a class="nav-link" href="<?= HOME ?>contact">Contact</a>
            </nav>
        </div>
    </header>

    <main class="px-3">
        <h1>Attention!!!</h1>
        <p class="lead">Page Not Found</p>
    </main>


    <?php require VIEWS_PATH . 'includes/footer.phtml'; ?>