<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0">Master Course</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link active" aria-current="page" href="<?= HOME ?>">Home</a>
                <a class="nav-link" href="<?= HOME ?>about">About</a>
                <a class="nav-link" href="<?= HOME ?>contact">Contact</a>
            </nav>
        </div>
    </header>

    <main class="px-3">
        <h1>Welcome to Master Course</h1>
        <p class="lead">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu venenatis erat, id porta lorem. 
        Suspendisse potenti. Maecenas eu vestibulum tellus, eget facilisis metus. Sed lectus sem, congue non accumsan sed, facilisis a odio. Duis aliquam molestie efficitur.
         Sed sem purus, lacinia nec justo at, euismod vulputate metus. Nam a rhoncus libero. Etiam aliquet sapien a semper gravida. Nullam feugiat volutpat tortor vel pharetra. 
        Donec lacinia efficitur enim, vitae dapibus quam ullamcorper eu. Quisque sit amet mollis magna, nec pellentesque odio. Etiam convallis tristique quam vel congue.
         Duis nec mi eu sem iaculis hendrerit. Vivamus cursus, risus sed tincidunt mollis, erat justo faucibus leo, in tempor est eros et metus.
        Integer tristique, nisi ut luctus bibendum, felis est posuere lacus, non luctus orci justo ut odio.
        </p>
    </main>


    <?php require VIEWS_PATH . 'includes/footer.phtml'; ?>