<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="<?php echo HOME ?>">Master Courses</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="<?php echo HOME ?>">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo HOME ?>about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo HOME ?>contact">Contact</a>
                </li>

            </ul>
        </div>
    </div>
</nav>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>